### ISSUE TITLE
Add Examples for godoc

### ISSUE THREAD

**Issue by jasonrichardsmith** [pipes-and-filters/filters#2]

**Comment by ghost** [comment]
Yes, this is totally necessary and 

add some screenshots of a running cli programming with an .yaml file opened in the side, this will bring newcomers to start using this library. 

Users are spending  5-10 seconds, in average,   looking a README page,
Currently, they don't know what it does, and you should show them in in the first eye-spot.

**Comment by jasonrichardsmith** [comment]
@kataras I am working on the gifs but I added examples and more docs, feedback if you have time would great.

**Comment by jasonrichardsmith** [comment]
Closing added examples, as well as example over http, and gif.
